### ISSUE TITLE
Автодобавление в друзья не работает

### ISSUE THREAD

**Issue by buvanenko** [LordRalInc/IDM#5]
Собственно, сабж. 
Пишу _!с +адвд_, в ответ сообщение о том, что автодобавление в друзья запущено.
Пишу _!с адвд_, в овтет сообщение о том, что автодобавление в друзья не работает.

Может дело в этом:
`2020-04-11 21:46:17 *** Python threads support is disabled. You can enable it with --enable-threads ***`

**Comment by Elchinchel** [comment]
Если это pythonanywhere, то да, threading там не работает (дальше недостоверная информация) причем даже с платной подпиской, там вместо этого есть Tasks

**Comment by buvanenko** [comment]
Ипользовал сторонний скрипт для автодобавления.
